#!/usr/bin/env bash
# configures a new Ubuntu machine to respect above requirements

sudo apt update && upgrade
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
